backend/app/character/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'character'

urlpatterns = [
    url('', views.editCharacters, name='editCharacters'),
]

backend/app/chattool/urls.py
from django.urls import path
from . import views

app_name = 'chattool'

urlpatterns = [
    path("", views.ChattoolView.as_view(), name="chattool"),
    path("<str:room_name>/", views.ChatRoomView.as_view(), name="rooms"),

]

backend/app/dice/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


app_name = 'dice'


urlpatterns = [
    path('', views.dice, name='dice'),
]

backend/app/game/urls.py
from django.urls import include, path

from game import views

app_name = "game"


extra_patterns = [
    path("", views.gameView.as_view(), name="game"),
    path("map/", include('maptool.urls')),
    path("chattool/", include('chattool.urls')),
]

urlpatterns = [
    path("games-list/", views.listGames.as_view(), name="games_list"),
    path("create-game/", views.createGame.as_view(), name="create_game"),
    path("update-game/<int:game_id>/",
         views.updateGame.as_view(), name="update_game"),
    path("delete-game/<int:game_id>/",
         views.deleteGame.as_view(), name="delete_game"),
    path("<int:game_id>/", include(extra_patterns)),
]

backend/app/settings/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'settings'

urlpatterns = [
    url('server-settings/', views.settingsView.as_view(), name='settings'),
    url('certbot/', views.certbotView.as_view(), name='certbot'),
]

backend/app/templates/base/nav/sidebar-left.html
<!-- Sidebar-left -->
<aside id="sidebar-left" class=" position-relative closed bg-dark sidebar">
    <div class="position-fixed fixed-container">
        <ul class=" link-color-white no-scrollbar  min-100-vh">
            <li class="nav-item">
                <a class="sidebar-link d-flex" href="/">
                    <span class="icon-holder"><i class="fa fa-home"></i></span>
                    <span class="title">Home</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="sidebar-link d-flex" href="{% url 'character:editCharacters' %}">
                    <span class="icon-holder"><i class="fa fa-user"></i></span>
                    <span class="title">Character</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="sidebar-link d-flex dropdown" href="{% url 'game:games_list' %}">
                    <span class="icon-holder"><i class="fa fa-spider"></i></span>
                    <span class="title">Games</span>
                </a>
                <ul>
                    <li><a href="{% url 'game:create_game' %}">Create game</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="sidebar-link d-flex" href="{% url 'chattool:chattool' %}">
                    <span class="icon-holder"><i class="fa fa-paper-plane"></i></span>
                    <span class="title">Chat</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="sidebar-link d-flex " data-toggle="modal" data-target="#myModal">
                    <span class="icon-holder"><i class="fa fa-form"></i></span>
                    <span class="title">Modal</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="sidebar-link d-flex" href="{% url 'dice:dice' %}">
                    <span class="icon-holder"><i class="fa fa-dice"></i></span>
                    <span class="title">Dice</span>
                </a>
            </li>
        </ul>
        <ul class=" link-color-white no-scrollbar  min-100-vh">
            <li class="nav-item">
                <a class="sidebar-link d-flex dropdown" href="{% url 'settings:settings' %}">
                    <span class="icon-holder"><i class="fa fa-wrench"></i></span>
                    <span class="title">Settings</span>
                </a>
                <ul>
                    <li><a href="{% url 'account_logout' %}">Logout</a></li>
                    <li><a href="{% url 'admin:index' %}">Django adminpanel</a></li>
                </ul>
            </li>


        </ul>

    </div>
</aside>

backend/app/templates/base/nav/sidebar-right.html
<!-- Sidebar-right -->
<aside id="sidebar-right" class=" position-relative closed bg-dark sidebar">
    <div class="position-fixed fixed-container">
        <ul class=" link-color-white no-scrollbar  min-100-vh">
            <li class="nav-item">
                <a class="sidebar-link d-flex" href="/">
                    <span class="icon-holder"><i class="fa fa-home"></i></span>
                    <span class="title">Home</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="sidebar-link d-flex" href="{% url 'character:editCharacters' %}">
                    <span class="icon-holder"><i class="fa fa-user"></i></span>
                    <span class="title">Character</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="sidebar-link d-flex dropdown" href="{% url 'game:games_list' %}">
                    <span class="icon-holder"><i class="fa fa-spider"></i></span>
                    <span class="title">Games</span>
                </a>
                <ul>
                    <li><a href="{% url 'game:create_game' %}">Create game</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="sidebar-link d-flex" href="{% url 'chattool:chattool' %}">
                    <span class="icon-holder"><i class="fa fa-paper-plane"></i></span>
                    <span class="title">Chat</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="sidebar-link d-flex " data-toggle="modal" data-target="#myModal">
                    <span class="icon-holder"><i class="fa fa-form"></i></span>
                    <span class="title">Modal</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="sidebar-link d-flex" href="{% url 'dice:dice' %}">
                    <span class="icon-holder"><i class="fa fa-dice"></i></span>
                    <span class="title">Dice</span>
                </a>
            </li>
        </ul>


    </div>
</aside>